package br.com.redclaw.zelda64player.randomizer.settings

import org.json.JSONArray
import org.json.JSONObject

/**
 * Result of validating a Plandomizer placement file.
 *
 * @property valid `true` when there are no blocking [errors].
 * @property errors Blocking problems (wrong container type, bad value type,
 *   oversized `file_hash`). A file with errors must not be submitted.
 * @property warnings Non-blocking observations (unknown keys, values outside
 *   the known enum sets). The file may still be submitted.
 * @property parsed The parsed [JSONObject] when the input was syntactically
 *   valid (even if it carries warnings/errors). `null` on parse failure.
 */
data class ValidationResult(
    val valid: Boolean,
    val errors: List<String>,
    val warnings: List<String>,
    val parsed: JSONObject?
)

/**
 * Validates a Plandomizer placement file (the OoTR distribution file) against
 * the known structure described in the OoTR wiki / `Plandomizer.py`.
 *
 * The validator is intentionally lenient about *values* (it only type-checks
 * containers and a few cheap value rules) so that new OoTR versions adding new
 * keys/values are not rejected. Unknown top-level keys that do **not** start
 * with `:` produce a warning (they are preserved but not understood); keys
 * starting with `:` are spoiler/autogenerated concepts and are ignored
 * silently.
 *
 * Pure (no Android dependencies) so it can be unit-tested on the JVM.
 */
object PlandomizerValidator {

    private val KNOWN_OBJECT_KEYS = setOf(
        "settings",
        "randomized_settings",
        "starting_items",
        "item_pool",
        "dungeons",
        "trials",
        "entrances",
        "locations",
        "gossip_stones",
        "custom_groups"
    )

    private val KNOWN_ARRAY_KEYS = setOf("file_hash")

    /**
     * Validate a placement JSON [string]. Syntactically invalid input yields a
     * single error and a `null` [ValidationResult.parsed].
     */
    fun validate(jsonString: String): ValidationResult {
        val trimmed = jsonString.trim()
        if (trimmed.isEmpty()) {
            return ValidationResult(false, listOf("Empty JSON"), emptyList(), null)
        }
        val obj = try {
            JSONObject(trimmed)
        } catch (e: Exception) {
            return ValidationResult(
                false,
                listOf("Invalid JSON: ${e.message}"),
                emptyList(),
                null
            )
        }
        return validate(obj)
    }

    /**
     * Validate an already-parsed placement [JSONObject].
     */
    fun validate(obj: JSONObject): ValidationResult {
        val errors = mutableListOf<String>()
        val warnings = mutableListOf<String>()

        val keys = obj.keys().asSequence().toList()
        for (key in keys) {
            when {
                key.startsWith(":") -> { /* spoiler/autogenerated: ignore */ }
                key in KNOWN_OBJECT_KEYS -> {
                    if (obj.get(key) !is JSONObject) {
                        errors.add("'$key' must be a JSON object")
                    }
                }
                key in KNOWN_ARRAY_KEYS -> {
                    val v = obj.get(key)
                    if (v !is JSONArray) {
                        errors.add("'$key' must be a JSON array")
                    } else if (v.length() > 5) {
                        errors.add("'file_hash' must have at most 5 entries (found ${v.length()})")
                    } else {
                        for (i in 0 until v.length()) {
                            val e = v.get(i)
                            if (e !== JSONObject.NULL && e !is String) {
                                errors.add("'file_hash' entry $i must be a string or null")
                            }
                        }
                    }
                }
                else -> warnings.add("Unknown key '$key' is not a recognized Plandomizer section")
            }
        }

        fun objectSection(name: String): JSONObject? {
            if (!obj.has(name)) return null
            val v = obj.get(name)
            if (v !is JSONObject) return null // already reported above
            return v
        }

        objectSection("starting_items")?.let { sec ->
            sec.keys().asSequence().forEach { k ->
                if (sec.get(k) !is Number) errors.add("starting_items['$k'] must be a number")
            }
        }
        objectSection("item_pool")?.let { sec ->
            sec.keys().asSequence().forEach { k ->
                val v = sec.get(k)
                if (v !is Number && v !is JSONObject) {
                    errors.add("item_pool['$k'] must be a number or an object")
                } else if (v is JSONObject && (!v.has("type") || !v.has("count"))) {
                    errors.add("item_pool['$k'] object must have 'type' and 'count'")
                }
            }
        }
        objectSection("dungeons")?.let { sec ->
            sec.keys().asSequence().forEach { k ->
                val v = sec.get(k)
                if (v !is String) {
                    errors.add("dungeons['$k'] must be a string")
                } else if (v !in PLANDOMIZER_DUNGEON_VALUES) {
                    warnings.add("dungeons['$k'] value '$v' is not a known mode (vanilla/mq/random)")
                }
            }
        }
        objectSection("trials")?.let { sec ->
            sec.keys().asSequence().forEach { k ->
                val v = sec.get(k)
                if (v !is String) {
                    errors.add("trials['$k'] must be a string")
                } else if (v !in PLANDOMIZER_TRIAL_VALUES) {
                    warnings.add("trials['$k'] value '$v' is not a known mode (active/inactive/random)")
                }
            }
        }
        objectSection("custom_groups")?.let { sec ->
            sec.keys().asSequence().forEach { k ->
                if (sec.get(k) !is JSONArray) errors.add("custom_groups['$k'] must be an array")
            }
        }

        return ValidationResult(errors.isEmpty(), errors, warnings, obj)
    }
}
